language: python

env:
  global:
    - MAKEFLAGS="-j 2"

services:
  - docker

script:
  - echo "---------- X11 IMAGES ----------"
  - docker build -f ./x11/Dockerfile --target base -t jgkawell/x11:base ./x11
  - docker build -f ./x11/Dockerfile --target nvidia --cache-from jgkawell/x11:base -t jgkawell/x11:base-nvidia ./x11

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
