#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# Push basic x11 images
docker push jgkawell/x11:base
docker push jgkawell/x11:base-nvidia

# Push basic ROS images
docker push jgkawell/ros:base
docker push jgkawell/ros:base-nvidia

# Push OMPL images
docker push jgkawell/ompl:base
docker push jgkawell/ompl:base-nvidia
docker push jgkawell/ompl:sawyer
docker push jgkawell/ompl:sawyer-nvidia
docker push jgkawell/ompl:lfd
docker push jgkawell/ompl:lfd-nvidia
