version: '3'
services:
  main:
    image: jgkawell/ompl:base
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    devices:
      - "/dev/dri:/dev/dri"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ompl-base
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "CONTAINER_NAME=ompl-base"
    stdin_open: true
    tty: true
