version: '3'
services:
  main:
    image: ${IMAGE}
    container_name: ${CONTAINER}
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_GRAPHICSSYSTEM=native"
      - "CONTAINER_NAME=${CONTAINER}"
    stdin_open: true
    tty: true
